# Generated by Django 4.2.5 on 2023-09-29 12:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('brand', models.CharField(max_length=256)),
                ('name', models.CharField(max_length=256)),
                ('manufacture_year', models.PositiveIntegerField()),
                ('fuel_type', models.CharField(choices=[('PETROL', 'Petrol'), ('DIESEL', 'Diesel'), ('CNG', 'CNG'), ('EV', 'Electric')], default='PETROL', max_length=256)),
                ('transmission_type', models.CharField(choices=[('MANUAL', 'Manual'), ('AUTOMATIC', 'Automatic')], default='MANUAL', max_length=256)),
                ('car_type', models.CharField(choices=[('SEDAN', 'Sedan'), ('HATCHBACK', 'Hatchback'), ('SUV', 'SUV'), ('COUPE', 'Coupe')], default='SEDAN', max_length=256)),
                ('seats', models.PositiveIntegerField()),
                ('registration_no', models.CharField(max_length=256, unique=True)),
                ('km_driven', models.PositiveBigIntegerField()),
                ('fare', models.PositiveIntegerField()),
                ('description', models.TextField(max_length=1000)),
                ('pickup_address', models.TextField()),
                ('pickup_city', models.CharField(max_length=256)),
                ('pickup_state', models.CharField(max_length=256)),
                ('pickup_country', models.CharField(max_length=256)),
                ('pickup_pincode', models.CharField(max_length=256)),
                ('is_available', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CarImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('car_images', models.ImageField(upload_to='car_images')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Rent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('pickup_datetime', models.DateTimeField()),
                ('drop_datetime', models.DateTimeField()),
                ('total_fare', models.FloatField()),
                ('payment_status', models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=256)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='car.car')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
