# Generated by Django 4.2.5 on 2023-10-02 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='total_hours',
            field=models.PositiveIntegerField(default=None),
        ),
    ]
