# Generated by Django 4.2.5 on 2023-10-02 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0003_rent_total_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='rent',
            name='booking_status',
            field=models.CharField(choices=[('CONFIRMED', 'Confirmed'), ('PICKEDUP', 'Pickedup'), ('DROPPED', 'Dropped'), ('CANCELLED', 'Cancelled')], default='CONFIRMED', max_length=256),
        ),
    ]
