# Generated by Django 4.2.5 on 2023-10-02 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0004_rent_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rent',
            name='payment_status',
            field=models.CharField(choices=[('COMPLETED', 'Completed'), ('PENDING', 'Pending'), ('CANCELLED', 'Cancelled'), ('REFUNDED', 'Refunded')], default='PENDING', max_length=256),
        ),
    ]
