# Generated by Django 4.2.5 on 2023-10-04 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0006_alter_rent_car_carholdtime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carholdtime',
            old_name='end_date',
            new_name='end_datetime',
        ),
        migrations.RenameField(
            model_name='carholdtime',
            old_name='start_date',
            new_name='start_datetime',
        ),
    ]
