# Generated by Django 4.2.5 on 2023-10-05 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('car', '0007_rename_end_date_carholdtime_end_datetime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carholdtime',
            name='car',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='car_carholdtime', to='car.car'),
        ),
    ]
